version: '3.8'

#sudo docker-compose down -v && sudo docker-compose -p linguanews up --build

services:
  newsdb:
    image: postgres
    container_name: newsdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: LinguaNewsDb
    restart: always
    ports:
      - "5439:5432"
    volumes:
      - postgres_linguanews:/var/lib/postgresql/data
  
  linguanews.api:
    container_name: linguanews.api
    build:
      context: .
      dockerfile: LinguaNews.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ## docker iletisim icin asil port verilir
      ConnectionStrings__Database: "Server=newsdb;Port=5432;Database=LinguaNewsDb;User Id=postgres;Password=postgres"
    depends_on:
      - newsdb
    ports:
      - "6009:8080"

volumes:
  postgres_linguanews:
